<a href="https://colab.research.google.com/github/amirmohammadkalateh/drug200-ANN/blob/TensorBoard/drug200_ANN_TensorBoard.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
import keras
from keras import layers
from keras import ops
from sklearn.model_selection import train_test_split

data = pd.read_csv('drug200.csv')


label_encoder_sex = LabelEncoder()
label_encoder_bp = LabelEncoder()
label_encoder_chol = LabelEncoder()
label_encoder_drug = LabelEncoder()


data['Sex'] = label_encoder_sex.fit_transform(data['Sex'])
data['BP'] = label_encoder_bp.fit_transform(data['BP'])
data['Cholesterol'] = label_encoder_chol.fit_transform(data['Cholesterol'])
data['Drug'] = label_encoder_drug.fit_transform(data['Drug'])


X = data.drop('Drug', axis=1)
y = data['Drug']


print(X.head())
print(y.head())

   Age  Sex  BP  Cholesterol  Na_to_K
0   23    0   0            0   25.355
1   47    1   1            0   13.093
2   47    1   1            0   10.114
3   28    0   2            0    7.798
4   61    0   1            0   18.043
0    4
1    2
2    2
3    3
4    4
Name: Drug, dtype: int64


In [ ]:
print(data.size)
print(data.shape)

1200
(200, 6)


In [ ]:
X = data [["Age" , "Sex" ,"BP" ,"Cholesterol" , "Na_to_K" ]]
y = data ["Drug"]
print(y[0:10])
print([X[0:10]])

0    4
1    2
2    2
3    3
4    4
5    3
6    4
7    2
8    4
9    4
Name: Drug, dtype: int64
[   Age  Sex  BP  Cholesterol  Na_to_K
0   23    0   0            0   25.355
1   47    1   1            0   13.093
2   47    1   1            0   10.114
3   28    0   2            0    7.798
4   61    0   1            0   18.043
5   22    0   2            0    8.607
6   49    0   2            0   16.275
7   41    1   1            0   11.037
8   60    1   2            0   15.171
9   43    1   1            1   19.368]


In [ ]:
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.3, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

In [ ]:
model = keras.Sequential([
    layers.Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    layers.Dense(32, activation='relu'),
    layers.Dense(5 , activation = "softmax")
])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
model.compile(optimizer='SGD',
              loss='mse',
              metrics=['mae'])

In [ ]:
model.fit(X_train,
          y_train,
          epochs=50,
          batch_size=32,
          validation_data=(X_val, y_val),
          verbose=1)

Epoch 1/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 65ms/step - loss: 9.2408 - mae: 2.7287 - val_loss: 8.6725 - val_mae: 2.6400
Epoch 2/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 9.1873 - mae: 2.7168 - val_loss: 8.6709 - val_mae: 2.6400
Epoch 3/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 8.8989 - mae: 2.6355 - val_loss: 8.6683 - val_mae: 2.6400
Epoch 4/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 9.5545 - mae: 2.7900 - val_loss: 8.6629 - val_mae: 2.6400
Epoch 5/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 9.3216 - mae: 2.7306 - val_loss: 8.6411 - val_mae: 2.6400
Epoch 6/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 9.0880 - mae: 2.7091 - val_loss: 8.5961 - val_mae: 2.6400
Epoch 7/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 9.1551 - mae: 2.7088 - val_loss: 8.5549 - val_mae: 2.6400
Epoch 8/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 9.1653 - mae: 2.7297 - val_loss: 8.5523 - val_mae: 2.6400
Epoch 9/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 8.9215 - mae: 2.6931 - 

# New Section

In [9]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [10]:
data = pd.read_csv('drug200.csv')

In [11]:
X = data.drop('Drug', axis=1)
y = data['Drug']

In [12]:
X = pd.get_dummies(X, columns=['Sex', 'BP', 'Cholesterol'], prefix=['Sex', 'BP', 'Cholesterol'])


In [13]:
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)


In [14]:
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.3, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

In [15]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_val = scaler.transform(X_val)
X_test = scaler.transform(X_test)

In [16]:
model = keras.Sequential([
    layers.Input(shape=(X_train.shape[1],)),
    layers.Dense(64, activation='relu'),
    layers.Dropout(0.2),
    layers.Dense(32, activation='relu'),
    layers.Dropout(0.2),
    layers.Dense(5, activation='softmax')
])

In [17]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])


In [31]:

history = model.fit(X_train, y_train,
                    epochs=50,
                    batch_size=32,
                    validation_data=(X_val, y_val),
                    callbacks=[tb_callback],
                    verbose=1)

Epoch 1/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 3s 118ms/step - accuracy: 0.2340 - loss: 1.6409 - val_accuracy: 0.1667 - val_loss: 1.5075
Epoch 2/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.3294 - loss: 1.4901 - val_accuracy: 0.2667 - val_loss: 1.4213
Epoch 3/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.4735 - loss: 1.3550 - val_accuracy: 0.3667 - val_loss: 1.3488
Epoch 4/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5321 - loss: 1.2967 - val_accuracy: 0.3667 - val_loss: 1.2884
Epoch 5/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.5726 - loss: 1.2339 - val_accuracy: 0.4333 - val_loss: 1.2360
Epoch 6/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.5193 - loss: 1.2248 - val_accuracy: 0.4667 - val_loss: 1.1883
Epoch 7/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5241 - loss: 1.1711 - val_accuracy: 0.4667 - val_loss: 1.1412
Epoch 8/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5948 - loss: 1.0965 - val_accuracy: 0.5000 - val_loss: 1.0997

In [19]:
predictions = model.predict(X_test)
print(model.predict(X_test))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 177ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
[[0.23789361 0.16210349 0.14202344 0.2484785  0.20950101]
 [0.24037257 0.19487518 0.18829203 0.20809385 0.16836646]
 [0.1632297  0.16257015 0.17283975 0.19657633 0.3047841 ]
 [0.22722791 0.19567962 0.17905389 0.17244934 0.22558911]
 [0.22266443 0.17387228 0.20958367 0.18038009 0.21349956]
 [0.23811439 0.18856855 0.1707393  0.23061764 0.17196012]
 [0.15999292 0.14793485 0.1773905  0.32539803 0.18928374]
 [0.11421597 0.20084772 0.23254119 0.21199097 0.24040419]
 [0.36216655 0.12322062 0.15923049 0.18334752 0.17203477]
 [0.12393314 0.17909232 0.20965093 0.30531156 0.18201193]
 [0.35562617 0.12442391 0.16114329 0.1796621  0.17914464]
 [0.16058879 0.24965763 0.16052338 0.27014542 0.15908487]
 [0.40914452 0.1002055  0.13805003 0.2022361  0.1503638 ]
 [0.21560027 0.19953041 0.18178548 0.16976473 0.23331924]
 [0.2610459  0.18219367 0.19861369 0.18355985 0.17458682]
 [0.16382933 0.24024606 0.13922063 0.3080969  0.14860

In [21]:
model.save('drug_classification_model.h5')

In [29]:
tb_callback = keras.callbacks.TensorBoard("tb_callback")